[2024-12-26T19:34:04.536+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-26T19:34:04.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HttpSensor_dag.wait_for_api scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2024-12-26T19:34:04.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HttpSensor_dag.wait_for_api scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2024-12-26T19:34:04.605+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-26T19:34:04.625+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): wait_for_api> on 2023-01-02 00:00:00+00:00
[2024-12-26T19:34:04.633+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=932) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-26T19:34:04.634+0000] {standard_task_runner.py:63} INFO - Started process 937 to run task
[2024-12-26T19:34:04.637+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'HttpSensor_dag', 'wait_for_api', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '1101', '--raw', '--subdir', 'DAGS_FOLDER/dag_http_sensor.py', '--cfg-path', '/tmp/tmpwd1p4kj5']
[2024-12-26T19:34:04.638+0000] {standard_task_runner.py:91} INFO - Job 1101: Subtask wait_for_api
[2024-12-26T19:34:04.703+0000] {task_command.py:426} INFO - Running <TaskInstance: HttpSensor_dag.wait_for_api scheduled__2023-01-02T00:00:00+00:00 [running]> on host 87a1e11545b0
[2024-12-26T19:34:04.939+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='HttpSensor_dag' AIRFLOW_CTX_TASK_ID='wait_for_api' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2024-12-26T19:34:04.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-26T19:34:05.019+0000] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-26T19:34:05.020+0000] {http.py:137} INFO - Poking: https://api.coindesk.com/v1/bpi/currentprice.json
[2024-12-26T19:34:05.064+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-26T19:34:05.089+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 158, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 167, in run
    session = self.get_conn(headers)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 108, in get_conn
    conn = self.get_connection(self.http_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_http_conn` isn't defined
[2024-12-26T19:34:05.096+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=HttpSensor_dag, task_id=wait_for_api, run_id=scheduled__2023-01-02T00:00:00+00:00, execution_date=20230102T000000, start_date=20241226T193404, end_date=20241226T193405
[2024-12-26T19:34:05.112+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1101 for task wait_for_api (The conn_id `my_http_conn` isn't defined; 937)
[2024-12-26T19:34:05.147+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-26T19:34:05.198+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T19:34:05.203+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
