[2024-12-26T19:34:17.396+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-26T19:34:17.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: HttpSensor_dag.wait_for_api scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2024-12-26T19:34:17.477+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: HttpSensor_dag.wait_for_api scheduled__2023-01-23T00:00:00+00:00 [queued]>
[2024-12-26T19:34:17.478+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-26T19:34:17.529+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): wait_for_api> on 2023-01-23 00:00:00+00:00
[2024-12-26T19:34:17.547+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=972) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-26T19:34:17.560+0000] {standard_task_runner.py:63} INFO - Started process 978 to run task
[2024-12-26T19:34:17.559+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'HttpSensor_dag', 'wait_for_api', 'scheduled__2023-01-23T00:00:00+00:00', '--job-id', '1122', '--raw', '--subdir', 'DAGS_FOLDER/dag_http_sensor.py', '--cfg-path', '/tmp/tmpt45i2wo9']
[2024-12-26T19:34:17.564+0000] {standard_task_runner.py:91} INFO - Job 1122: Subtask wait_for_api
[2024-12-26T19:34:17.723+0000] {task_command.py:426} INFO - Running <TaskInstance: HttpSensor_dag.wait_for_api scheduled__2023-01-23T00:00:00+00:00 [running]> on host 87a1e11545b0
[2024-12-26T19:34:18.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='HttpSensor_dag' AIRFLOW_CTX_TASK_ID='wait_for_api' AIRFLOW_CTX_EXECUTION_DATE='2023-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-23T00:00:00+00:00'
[2024-12-26T19:34:18.119+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-26T19:34:18.169+0000] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-12-26T19:34:18.170+0000] {http.py:137} INFO - Poking: https://api.coindesk.com/v1/bpi/currentprice.json
[2024-12-26T19:34:18.195+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-26T19:34:18.225+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 158, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 167, in run
    session = self.get_conn(headers)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 108, in get_conn
    conn = self.get_connection(self.http_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_http_conn` isn't defined
[2024-12-26T19:34:18.235+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=HttpSensor_dag, task_id=wait_for_api, run_id=scheduled__2023-01-23T00:00:00+00:00, execution_date=20230123T000000, start_date=20241226T193417, end_date=20241226T193418
[2024-12-26T19:34:18.252+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1122 for task wait_for_api (The conn_id `my_http_conn` isn't defined; 978)
[2024-12-26T19:34:18.284+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-26T19:34:18.323+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T19:34:18.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
