[2024-12-21T10:56:51.652+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: email_example.send_email scheduled__2024-12-20T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
